/*
 * Studio constants
 */


export const VFX_REQUEST = 'app/VFX/VFX_REQUEST';
export const VFX_SUCCESS = 'app/VFX/VFX_SUCCESS';
export const VFX_ERROR = 'app/VFX/VFX_ERROR';
export const SEARCH_VFX_REQUEST = 'app/VFX/SEARCH_STUDIO_REQUEST';
export const SEARCH_VFX_SUCCESS = 'app/VFX/SEARCH_STUDIO_SUCCESS';
export const SEARCH_VFX_ERROR = 'app/VFX/SEARCH_STUDIO_ERROR';
export const TOGGLE_SEARCH = 'app/VFX/TOGGLE_SEARCH';
export const NEXT_PAGE_REQUEST = 'app/VFX/NEXT_PAGE_REQUEST';
export const NEXT_PAGE_SUCCESS = 'app/VFX/NEXT_PAGE_SUCCESS';
export const NEXT_PAGE_ERROR = 'app/VFX/NEXT_PAGE_ERROR';
export const START_SPINNER = 'app/VFX/START_SPINNER';
export const ADD_STUDIO_REQUEST = 'app/VFX/ADD_STUDIO_REQUEST';
export const ADD_STUDIO_SUCCES = 'app/VFX/ADD_STUDIO_SUCCES';
export const GET_RECRUITER_STUDIO_REQUEST = 'app/VFX/GET_RECRUITER_STUDIO_REQUEST';
export const GET_RECRUITER_STUDIO_SUCCESS = 'app/VFX/GET_RECRUITER_STUDIO_SUCCESS';
export const GET_RECRUITER_STUDIO_ERROR = 'app/VFX/GET_RECRUITER_STUDIO_ERROR';
