
export const SEARCH_SALARY_REQUEST = 'SEARCH_SALARY_REQUEST';
export const SEARCH_SALARY_SUCCESS = 'SEARCH_SALARY_SUCCESS';
export const SEARCH_SALARY_ERROR = 'SEARCH_SALARY_ERROR';

export const GET_JOBTITLE_REQUEST = 'GET_JOBTITLE_REQUEST';

export const GET_JOBS_REQUEST = 'GET_JOBS_REQUEST';
export const GET_JOBS_SUCCESS = 'GET_JOBS_SUCCESS';

export const GET_JOBS_BYNAME_REQUEST = 'GET_JOBS_BYNAME_REQUEST';
export const SAVE_TITLES = 'SAVE_TITLES';

