/*
 * App constants
 */

import { getUserGamesAndMakersRequest } from './actions';

export const DIRECT_SIGNUP_REQUEST = 'app/App/DIRECT_SIGNUP_REQUEST';
export const DIRECT_SIGNUP_SUCCESS = 'app/App/DIRECT_SIGNUP_SUCCESS';
export const DIRECT_SIGNUP_ERROR = 'app/App/DIRECT_SIGNUP_ERROR';

export const SIGNUP_REQUEST = 'app/App/SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'app/App/SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'app/App/SIGNUP_ERROR';

export const LOGIN_REQUEST = 'app/App/LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'app/App/LOGIN_SUCCESS';
export const LOGIN_ERROR = 'app/App/LOGIN_ERROR';

export const PASSWORD_LINK_REQUEST = 'app/App/PASSWORD_LINK_REQUEST';
export const PASSWORD_LINK_SUCCESS = 'app/App/PASSWORD_LINK_SUCCESS';
export const PASSWORD_LINK_ERROR = 'app/App/PASSWORD_LINK_ERROR';

export const UPDATE_PASSWORD_REQUEST = 'app/App/UPDATE_PASSWORD_REQUEST';
export const UPDATE_PASSWORD_SUCCESS = 'app/App/UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_ERROR = 'app/App/UPDATE_PASSWORD_ERROR';

export const LOGOUT_REQUEST = 'app/App/LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'app/App/LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'app/App/LOGOUT_ERROR';

export const USER_REQUEST = 'app/App/USER_REQUEST';
export const USER_SUCCESS = 'app/App/USER_SUCCESS';
export const USER_ERROR = 'app/App/USER_ERROR';

export const PENDING_REQUEST = 'app/App/PENDING_REQUEST';
export const PENDING_SUCCESS = 'app/App/PENDING_SUCCESS';
export const PENDING_ERROR = 'app/App/PENDING_ERROR';

export const ACCEPT_REQUEST = 'app/App/ACCEPT_REQUEST';
export const ACCEPT_SUCCESS = 'app/App/ACCEPT_SUCCESS';
export const ACCEPT_ERROR = 'app/App/ACCEPT_ERROR';

export const REJECT_REQUEST = 'app/App/REJECT_REQUEST';
export const REJECT_SUCCESS = 'app/App/REJECT_SUCCESS';
export const REJECT_ERROR = 'app/App/REJECT_ERROR';

export const MESSAGE_REQUEST = 'app/App/MESSAGE_REQUEST';
export const MESSAGE_SUCCESS = 'app/App/MESSAGE_SUCCESS';
export const MESSAGE_ERROR = 'app/App/MESSAGE_ERROR';

export const STUDIO_MESSAGE_REQUEST = 'app/App/STUDIO_MESSAGE_REQUEST';
export const STUDIO_MESSAGE_ERROR = 'app/App/STUDIO_MESSAGE_ERROR';
export const STUDIO_MESSAGE_SUCCESS = 'app/App/STUDIO_MESSAGE_SUCCESS';

export const APPLICANT_MESSAGE_SUCCESS = 'app/App/APPLICANT_MESSAGE_SUCCESS';
export const APPLICANT_MESSAGE_ERROR = 'app/App/APPLICANT_MESSAGE_ERROR';
export const APPLICANT_MESSAGE_REQUEST = 'app/App/APPLICANT_MESSAGE_REQUEST';

export const INVITE_REQUEST = 'app/App/INVITE_REQUEST';
export const INVITE_SUCCESS = 'app/App/INVITE_SUCCESS';
export const INVITE_ERROR = 'app/App/INVITE_ERROR';

export const INVITE_MEMBER_REQUEST = 'app/App/INVITE_MEMBER_REQUEST';
export const INVITE_MEMBER_SUCCESS = 'app/App/INVITE_MEMBER_SUCCESS';
export const INVITE_MEMBER_ERROR = 'app/App/INVITE_MEMBER_ERROR';

export const CONNECT_REQUEST = 'app/App/CONNECT_REQUEST';
export const CONNECT_SUCCESS = 'app/App/CONNECT_SUCCESS';
export const CONNECT_ERROR = 'app/App/CONNECT_ERROR';

export const ADD_EXP_REQUEST = 'app/App/ADD_EXP_REQUEST';
export const ADD_EXP_SUCCESS = 'app/App/ADD_EXP_SUCCESS';
export const ADD_EXP_ERROR = 'app/App/ADD_EXP_ERROR';

export const EDIT_EXP_REQUEST = 'app/App/EDIT_EXP_REQUEST';
export const EDIT_EXP_SUCCESS = 'app/App/EDIT_EXP_SUCCESS';
export const EDIT_EXP_ERROR = 'app/App/EDIT_EXP_ERROR';

export const DELETE_EXP_REQUEST = 'app/App/DELETE_EXP_RQUEST';
export const DELETE_EXP_SUCCESS = 'app/App/DELETE_EXP_SUCCESS';
export const DELETE_EXP_ERROR = 'app/App/DELETE_EXP_ERROR';

export const APPLY_SMS_REQUEST = 'app/App/APPLY_SMS_REQUEST';
export const APPLY_SMS_SUCCESS = 'app/App/APPLY_SMS_SUCCESS';
export const APPLY_SMS_ERROR = 'app/App/APPLY_SMS_ERROR';

export const CONFIRM_CODE_REQUEST = 'app/App/CONFIRM_CODE_REQUEST';
export const CONFIRM_CODE_SUCCESS = 'app/App/CONFIRM_CODE_SUCCESS';
export const CONFIRM_CODE_ERROR = 'app/App/CONFIRM_CODE_ERROR';

export const CREDITS_REQUEST = 'app/App/CREDITS_REQUEST';
export const CREDITS_SUCCESS = 'app/App/CREDITS_SUCCESS';
export const CREDITS_ERROR = 'app/App/CREDITS_ERROR';

export const GET_AUTOCOMPLETE_REQUEST = 'app/AutoComplete/GET_AUTOCOMPLETE_REQUEST';
export const GET_AUTOCOMPLETE_SUCCESS = 'app/AutoComplete/GET_AUTOCOMPLETE_SUCCESS';
export const GET_AUTOCOMPLETE_ERROR = 'app/AutoComplete/GET_AUTOCOMPLETE_ERROR';

export const UPDATE_DETAILS_REQUEST = 'app/App/UPDATE_DETAILS_REQUEST';
export const UPDATE_DETAILS_SUCCESS = 'app/App/UPDATE_DETAILS_SUCCESS';
export const UPDATE_DETAILS_ERROR = 'app/App/UPDATE_DETAILS_ERROR';

export const UPDATE_EDUCATION_REQUEST = 'app/App/UPDATE_EDUCATION_REQUEST';
export const UPDATE_EDUCATION_SUCCESS = 'app/App/UPDATE_EDUCATION_SUCCESS';
export const UPDATE_EDUCATION_ERROR = 'app/App/UPDATE_EDUCATION_ERROR';

export const UPDATE_OPPORTUNITIES_REQUEST = 'app/App/UPDATE_OPPORTUNITIES_REQUEST';
export const UPDATE_OPPORTUNITIES_SUCCESS = 'app/App/UPDATE_OPPORTUNITIES_SUCCESS';
export const UPDATE_OPPORTUNITIES_ERROR = 'app/App/UPDATE_OPPORTUNITIES_ERROR';

export const AVAILABILITY_REQUEST = 'app/App/AVAILABILITY_REQUEST';
export const AVAILABILITY_SUCCESS = 'app/App/AVAILABILITY_SUCCESS';
export const AVAILABILITY_ERROR = 'app/App/AVAILABILITY_ERROR';

export const LOCATION_REQUEST = 'app/App/LOCATION_REQUEST';
export const LOCATION_SUCCESS = 'app/App/LOCATION_SUCCESS';
export const LOCATION_ERROR = 'app/App/LOCATION_ERROR';

export const GET_COUNTRIES_REQUEST = 'app/App/GET_COUNTRIES_REQUEST';
export const GET_COUNTRIES_SUCCESS = 'app/App/GET_COUNTRIES_SUCCESS';
export const GET_COUNTRIES_ERROR = 'app/App/GET_COUNTRIES_ERROR';

export const GET_STATES_REQUEST = 'app/App/GET_STATES_REQUEST';
export const GET_STATES_SUCCESS = 'app/App/GET_STATES_SUCCESS';
export const GET_STATES_ERROR = 'app/App/GET_STATES_ERROR';

export const GET_CITIES_REQUEST = 'app/App/GET_CITIES_REQUEST';
export const GET_CITIES_SUCCESS = 'app/App/GET_CITIES_SUCCESS';
export const GET_STATE_CITIES_SUCCESS = 'app/App/GET_STATE_CITIES_SUCCESS';
export const GET_CITIES_ERROR = 'app/App/GET_CITIES_ERROR';

export const PENDING_TEAM_REQUEST = 'app/App/PENDING_TEAM_REQUEST';
export const PENDING_TEAM_SUCCESS = 'app/App/PENDING_TEAM_SUCCESS';
export const PENDING_TEAM_ERROR = 'app/App/PENDING_TEAM_ERROR';

export const ACCEPT_TEAM_REQUEST = 'app/App/ACCEPT_TEAM_REQUEST';
export const TEAM_REQUEST_SUCCESS = 'app/App/TEAM_REQUEST_SUCCESS';
export const ACCEPT_TEAM_ERROR = 'app/App/ACCEPT_TEAM_ERROR';

export const REJECT_TEAM_REQUEST = 'app/App/REJECT_TEAM_REQUEST';
export const REJECT_TEAM_ERROR = 'app/App/REJECT_TEAM_ERROR';

export const INVITE_MAKER_REQUEST = 'app/App/INVITE_MAKER_REQUEST';
export const INVITE_MAKER_ERROR = 'app/App/INVITE_MAKER_ERROR';

export const CLAIM_PROFILE_REQUEST = 'app/App/CLAIM_PROFILE_REQUEST';
export const CLAIM_PROFILE_ERROR = 'app/App/CLAIM_PROFILE_ERROR';

export const CHECK_CATEGORIES = 'app/App/CHECK_CATEGORIES';

export const STUDIO_HUB_REQUEST = 'app/APP/STUDIO_HUB_REQUEST';

export const VALIDATE_TOKEN_REQUEST = 'app/APP/VALIDATE_TOKEN_REQUEST';

export const SET_PASSWORD_REQUEST = 'app/APP/SET_PASSWORD_REQUEST';

export const SEND_JOB_TO_FRIEND_REQUEST = 'app/APP/SEND_JOB_TO_FRIEND_REQUEST';
export const SAVE_JOB_FOR_LATER = 'app/Job/SAVE_JOB_FOR_LATER';
export const CONFIRM_JOB_REPOST = 'app/Job/CONFIRM_JOB_REPOST';

export const DELETE_CV_REQUEST = 'app/APP/DELETE_CV_REQUEST';
export const GET_MAKER_CV_INFO = 'app/APP/GET_MAKER_CV_INFO';

export const MAKER_CV_SUCCESS = 'app/APP/MAKER_CV_SUCCESS';

export const GET_COMPANY_INFO = 'app/APP/GET_COMPANY_INFO';
export const COMPANY_INFO_SUCCESS = 'app/APP/COMPANY_INFO_SUCCESS';

export const SELECTED_CV = 'app/APP/SELECTED_CV';

export const ADD_SUBSCRIBER_REQUEST = 'app/APP/ADD_SUBSCRIBER_REQUEST';

export const ADD_PASSION_REQUEST = 'app/APP/ADD_PASSION_REQUEST';

export const ADD_APPLOZIC_COUNT_REQUEST = 'app/APP/ADD_APPLOZIC_COUNT_REQUEST';
export const ADD_APPLOZIC_COUNT_SUCCESS = 'app/APP/ADD_APPLOZIC_COUNT_SUCCESS';

export const GET_APPLOZIC_COUNT_REQUEST = 'app/APP/GET_APPLOZIC_COUNT_REQUEST';
export const GET_APPLOZIC_COUNT_SUCCESS = 'app/APP/GET_APPLOZIC_COUNT_SUCCESS';
export const GET_APPLOZIC_COUNT_ERROR = 'app/APP/GET_APPLOZIC_COUNT_ERROR';

export const GET_APPLOZIC_RECRUITER_REQUEST = 'app/APP/GET_APPLOZIC_RECRUITER_REQUEST';
export const GET_APPLOZIC_RECRUITER_SUCCESS = 'app/APP/GET_APPLOZIC_RECRUITER_SUCCESS';

export const PROFILE_VIEW_COUNT_REQUEST = 'app/APP/PROFILE_VIEW_COUNT_REQUEST';
export const PROFILE_VIEW_COUNT_SUCCESS = 'app/APP/PROFILE_VIEW_COUNT_SUCCESS';

export const CHECK_PHONE_NUMBER_REQUEST = 'app/APP/CHECK_PHONE_NUMBER_REQUEST';

export const GAME_MAKER_REQEUST = 'app/APP/GAME_MAKER_REQEUST';
export const GAME_MAKER_SUCCESS = 'app/APP/GAME_MAKER_SUCCESS';
export const GAME_MAKER_ERROR = 'app/APP/GAME_MAKER_ERROR';

export const SEARCH_GAME_MAKERS_REQEUST = 'app/APP/SEARCH_GAME_MAKERS_REQEUST';
export const SEARCH_GAME_MAKERS_SUCCESS = 'app/APP/SEARCH_GAME_MAKERS_SUCCESS';
export const SEARCH_GAME_MAKERS_ERROR = 'app/APP/SEARCH_GAME_MAKERS_ERROR';

export const SEND_INVITE_REQUEST = 'app/APP/SEND_INVITE_REQEUST';
export const SEND_INVITE_SUCCESS = 'app/APP/SEND_INVITE_SUCCESS';
export const SEND_INVITE_ERROR = 'app/APP/SEND_INVITE_ERROR';

export const VERIFY_CREDIT_TOKEN_REQUEST = 'app/App/VERIFY_CREDIT_TOKEN_REQUEST';
export const VERIFY_CREDIT_TOKEN_SUCCESS = 'app/App/VERIFY_CREDIT_TOKEN_SUCCESS';
export const VERIFY_CREDIT_TOKEN_ERROR = 'app/App/VERIFY_CREDIT_TOKEN_ERROR';

export const IGNORE_VERIFICATION_REQUEST = 'app/App/IGNORE_VERIFICATION_REQUEST';

export const USER_GAME_AND_MAKERS_REQUEST = 'app/App/USER_GAME_AND_MAKERS_REQUEST';
export const USER_GAME_AND_MAKERS_SUCCESS = 'app/App/USER_GAME_AND_MAKERS_SUCCESS';
export const USER_GAME_AND_MAKERS_ERROR = 'app/App/USER_GAME_AND_MAKERS_ERROR';

export const MORE_MAKER_REQUEST = 'app/App/MORE_MAKER_REQUEST';
export const MORE_MAKER_SUCCESS = 'app/App/MORE_MAKER_SUCCESS';
export const MORE_MAKER_ERROR = 'app/App/MORE_MAKER_ERROR';
export const REMOVE_CREDIT = 'app/App/REMOVE_CREDIT';

export const GET_JWT_TOKEN_REQUEST = 'app/App/GET_JWT_TOKEN_REQUEST';
export const GET_JWT_TOKEN_SUCCESS = 'app/App/GET_JWT_TOKEN_SUCCESS';
export const GET_JWT_TOKEN_ERROR = 'app/App/GET_JWT_TOKEN_ERROR';

export const GET_ACCOUNT_ID_BY_NAME = 'app/App/GET_ACCOUNT_ID_BY_NAME';

export const SAVE_SLUG_REQUEST = 'app/App/SAVE_SLUG_REQUEST';
